name: Terraform Automation

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to the desired Terraform version
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == 'your_username'
        run: |
          terraform apply -input=false -auto-approve
          echo "::set-output name=public_ip::$(terraform output public_ip)"
      
      - name: Use EC2 Public IP
        run: |
          echo "EC2 Public IP: ${{ steps.terraform.outputs.public_ip }}"
          # Here you can perform actions using the public IP address of the EC2 instance
